---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcgis-readonly
  namespace: ""
rules:
  - apiGroups:
      - apps.mas.ibm.com/v1
    resources:
      - arcgisapps
      - arcgisworkspaces
    verbs:
      - get
      - list
      - watch
