apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../operators/certified-operator-catalog
patches:
  - target:
      kind: CatalogSource
      name: certified-operators
    patch: |-
      - op: replace
        path: /spec/image
        value: registry.redhat.io/redhat/certified-operator-index:v4.18
