---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:suite:visualinspection
  namespace: mas-{{ mas_instance_id }}-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:core:suite:visualinspection
subjects:
  - kind: ServiceAccount
    name: ibm-mas-visualinspection-entitymgr-primary-entity
    namespace: mas-{{ mas_instance_id }}-visualinspection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:core:suite:visualinspection
  namespace: mas-{{ mas_instance_id }}-core
rules:
  - apiGroups:
      - apps.mas.ibm.com
    resources:
      - Suite
    verbs:
      - get
