---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-mas-visualinspection-operator-group
  namespace: mas-x-visualinspection
spec:
  targetNamespaces:
    - mas-x-visualinspection
