---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: aiservice-dev1
resources:
  - ../../../../catalogs/maximo-operator-catalog/v9-251127-amd64/ibm-aiservice/9.1
  - ../../../../catalogs/maximo-operator-catalog/v9-251127-amd64/ibm-truststore-mgr
patches:
  - target:
      kind: OperatorGroup
      name: ibm-aiservice-operator-group
      namespace: ""
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value:
          - aiservice-dev1
