---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sls-admin
  namespace: ""
rules:
  - apiGroups:
      - sls.ibm.com
    resources:
      - licenseservices
      - licenseclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
