---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:coreapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mas:{{ mas_instance_id }}:core:coreapi
subjects:
  - kind: ServiceAccount
    name: ibm-mas-coreapi
    namespace: mas-{{ mas_instance_id }}-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mas:{{ mas_instance_id }}:core:coreapi
rules:
  # CoreAPI will check for the existence (and status) of the application CRDs
  # This is the ONLY cluster-scoped permission needed for CoreAPI
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
    resourceNames:
      # Core MAS CRDs
      - suites.core.mas.ibm.com
      - workspaces.core.mas.ibm.com
      - coreidps.internal.mas.ibm.com
      
      # Config CRDs
      - idpcfgs.config.mas.ibm.com
      - slscfgs.config.mas.ibm.com
      - smtpcfgs.config.mas.ibm.com
      - bascfgs.config.mas.ibm.com
      - jdbccfgs.config.mas.ibm.com
      - mongocfgs.config.mas.ibm.com
      - kafkacfgs.config.mas.ibm.com
      - objectstoragecfgs.config.mas.ibm.com
      - watsonstudiocfgs.config.mas.ibm.com
      - pushnotificationcfgs.config.mas.ibm.com
      - appcfgs.config.mas.ibm.com
      - scimcfgs.config.mas.ibm.com
      
      # Application CRDs
      - manageapps.apps.mas.ibm.com
      - healthapps.apps.mas.ibm.com
      - monitorapps.apps.mas.ibm.com
      - predictapps.apps.mas.ibm.com
      - assistapps.apps.mas.ibm.com
      - optimizerapps.apps.mas.ibm.com
      - visualinspectionapps.apps.mas.ibm.com
      - facilitiesapps.apps.mas.ibm.com
      - msoapps.apps.mas.ibm.com
      - safetyapps.apps.mas.ibm.com
      - hputilitiesapps.apps.mas.ibm.com
      
      # Application Workspace CRDs
      - manageworkspaces.apps.mas.ibm.com
      - healthworkspaces.apps.mas.ibm.com
      - monitorworkspaces.apps.mas.ibm.com
      - predictworkspaces.apps.mas.ibm.com
      - assistworkspaces.apps.mas.ibm.com
      - optimizerworkspaces.apps.mas.ibm.com
      - visualinspectionappworkspaces.apps.mas.ibm.com
      - facilitiesworkspaces.apps.mas.ibm.com
      - healthextworkspaces.apps.mas.ibm.com
      - msoworkspaces.apps.mas.ibm.com
      - safetyworkspaces.apps.mas.ibm.com
      - hputilitiesworkspaces.apps.mas.ibm.com
      
      # Manage-specific CRDs
      - manageaccelerators.apps.mas.ibm.com
      - managebuilds.apps.mas.ibm.com
      - managedeployments.apps.mas.ibm.com
      - manageofflineupgraderequests.apps.mas.ibm.com
      - manageserverbundles.apps.mas.ibm.com
      - managestatuscheckers.apps.mas.ibm.com
      
      # Other application-specific CRDs
      - aipoptimizations.apps.mas.ibm.com
      - builddatainterpreters.apps.mas.ibm.com
      - imagestitchings.apps.mas.ibm.com
      - opentelemetrydeployments.apps.mas.ibm.com
      - slackproxies.apps.mas.ibm.com
      
      # Addon CRDs
      - mviedges.addons.mas.ibm.com
      - genericaddons.addons.mas.ibm.com
      - replicadbs.addons.mas.ibm.com
      
      # IoT CRDs
      - iots.iot.ibm.com
      - iotworkspaces.iot.ibm.com
