---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:internalapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mas:{{ mas_instance_id }}:core:internalapi
subjects:
  - kind: ServiceAccount
    name: ibm-mas-internalapi
    namespace: mas-{{ mas_instance_id }}-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mas:{{ mas_instance_id }}:core:internalapi
rules:
  # A bug in mas-utils-py is resulting in us listing subscriptions globally instead of just in the application namespace
  # - This permission needs to be removed, and mas-utils-py code fixed to use the application namespace
  # https://github.ibm.com/maximoappsuite/mas-utils-py/blob/master/src/mas/utils/user/userUtil.py#L387
  # https://github.ibm.com/maximoappsuite/mas-utils-py/blob/master/src/mas/utils/user/userUtil.py#L543
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - get
      - list
