---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:core:coreapi:facilities
  namespace: mas-{{ mas_instance_id }}-facilities
rules:

  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get

  # Ability to install an operator in the namespace
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - operatorgroups
      - subscriptions
    verbs:
      - get
      - list
      - create
      - patch

  # Ability to get, create, and modify the MAS application in this namespace
  - apiGroups:
      - apps.mas.ibm.com
    resources:
      - facilitiesapps
      - facilitiesworkspaces
    verbs:
      - get
      - create
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:coreapi:facilities
  namespace: mas-{{ mas_instance_id }}-facilities
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:core:coreapi:facilities
subjects:
  - kind: ServiceAccount
    name: ibm-mas-coreapi
    namespace: mas-{{ mas_instance_id }}-core
