---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: redhat-marketplace
spec:
  name: openshift-cert-manager-operator
  channel: stable-v1

  installPlanApproval: Automatic

  source: redhat-operators
  sourceNamespace: openshift-marketplace
