apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../operators/ibm-operator-catalog
patches:
  - target:
      kind: CatalogSource
      name: ibm-operator-catalog
    patch: |-
      - op: replace
        path: /spec/displayName
        value: IBM Maximo Operators (v9-260108-amd64)
      - op: replace
        path: /spec/image
        value: icr.io/cpopen/ibm-maximo-operator-catalog:v9-260108-amd64
