---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-visualinspection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:internalapi:visualinspection
  namespace: mas-{{ mas_instance_id }}-visualinspection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:core:internalapi:visualinspection
subjects:
  - kind: ServiceAccount
    name: ibm-mas-internalapi
    namespace: mas-{{ mas_instance_id }}-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:core:internalapi:visualinspection
  namespace: mas-{{ mas_instance_id }}-visualinspection
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get

  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - get

  - apiGroups:
      - apps.mas.ibm.com
    resources:
      - visualinspectionapps
      - visualinspectionworkspaces
    verbs:
      - get
