apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../operators/ibm-aiservice
patches:
  - target:
      kind: Subscription
      name: ibm-aiservice
    patch: |-
      - op: replace
        path": /spec/channel
        value: 9.2.x-feature
      - op: replace
        path: /spec/startingCSV
        value: ibm-aiservice.v9.2.0-pre.stable_6741
