---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas-admin
  namespace: ""
rules:
  - apiGroups:
      - core.mas.ibm.com
    resources:
      - suites
      - workspaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.mas.ibm.com
    resources:
      - appcfgs
      - bascfgs
      - idpcfgs
      - jdbccfgs
      - kafkacfgs
      - mongocfgs
      - objectstoragecfgs
      - pushnotificationcfgs
      - scimcfgs
      - slscfgs
      - smtpcfgs
      - watsonstudiocfgs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - addons.mas.ibm.com
    resources:
      - genericaddons
      - mviedges
      - replicadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - internal.mas.ibm.com
    resources:
      - coreidp
    verbs:
      - get
      - list
      - watch
