---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operators
  namespace: openshift-marketplace
spec:
  displayName: Certified Operators
  publisher: Red Hat
  sourceType: grpc
  image: ""
