---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-metrics-operator
  namespace: ibm-software-central
spec:
  name: ibm-metrics-operator
  channel: stable

  installPlanApproval: Automatic

  source: certified-operators
  sourceNamespace: openshift-marketplace
