apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../operators/ibm-mas-predict
patches:
  - target:
      kind: Subscription
      name: ibm-mas-predict
    patch: |-
      - op: replace
        path": /spec/channel
        value: 9.1.x
      - op: replace
        path: /spec/startingCSV
        value: ibm-mas-predict.v9.1.3
