apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../operators/ibm-metrics
patches:
  - target:
      kind: Subscription
      name: ibm-metrics-operator
    patch: |-
      - op: replace
        path: /spec/startingCSV
        value: ibm-metrics-operator.v2.23.1
