---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mas-optimizer-operator
  namespace: mas-x-optimizer
spec:
  name: ibm-mas-optimizer
  channel: ""
  startingCSV: ""

  installPlanApproval: Automatic

  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
