apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../operators/ibm-mas-visualinspection
patches:
  - target:
      kind: Subscription
      name: ibm-mas-visualinspection-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 9.0.x
      - op: replace
        path: /spec/startingCSV
        value: ibm-mas-visualinspection.v9.0.13
