---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: mas-dev1-arcgis
resources:
  - ../../../../catalogs/maximo-operator-catalog/v9-251127-amd64/ibm-mas-arcgis/9.1
patches:
  - target:
      kind: OperatorGroup
      name: ibm-mas-arcgis-operator-group
      namespace: ""
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value:
          - mas-dev1-arcgis
