---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: visualinspection-admin
  namespace: ""
rules:
  - apiGroups:
      - apps.mas.ibm.com/v1
    resources:
      - visualinspectionapps
      - visualinspectionworkspaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
