apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../operators/ibm-mas-monitor
patches:
  - target:
      kind: Subscription
      name: ibm-mas-monitor-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 9.1.x
      - op: replace
        path: /spec/startingCSV
        value: ibm-mas-monitor.v9.1.4
