---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:core:internalapi:manage
  namespace: mas-{{ mas_instance_id }}-manage
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get

  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:internalapi:manage
  namespace: mas-{{ mas_instance_id }}-manage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:core:internalapi:manage
subjects:
  - kind: ServiceAccount
    name: ibm-mas-internalapi
    namespace: mas-{{ mas_instance_id }}-core
