---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./mas-dev1-core
  - ./mas-dev1-manage
  - ./mas-dev1-visualinspection
  - ./mas-dev1-sls
patches:
  # Example to use a specific catalog source for this MAS instance & set the install plan approval mode to "Manual"
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /spec/source
        value: maximo-catalog-dev1
      - op: replace
        path: /spec/installPlanApproval
        value: Manual
