---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ mas_instance_id }}-{{ mas_app_id }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mas:{{ mas_instance_id }}:core:coreapi:{{ mas_app_id }}
  namespace: mas-{{ mas_instance_id }}-{{ mas_app_id }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mas:{{ mas_instance_id }}:core:coreapi:{{ mas_app_id }}
subjects:
  - kind: ServiceAccount
    name: ibm-mas-coreapi
    namespace: mas-{{ mas_instance_id }}-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mas:{{ mas_instance_id }}:core:coreapi:{{ mas_app_id }}
  namespace: mas-{{ mas_instance_id }}-{{ mas_app_id }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
      - delete

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - delete
