apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../operators/ibm-truststore-mgr
patches:
  - target:
      kind: Subscription
      name: ibm-truststore-mgr
    patch: |-
      - op: replace
        path: /spec/startingCSV
        value: ibm-truststore-mgr.v1.7.2-ppc64le
