---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mas-monitor-operator
  namespace: mas-x-monitor
spec:
  name: ibm-mas-monitor
  channel: ""
  startingCSV: ""

  installPlanApproval: Automatic

  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
